# Generated by Django 3.2.5 on 2021-07-17 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postlike_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
