version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=WmZb1xeOkcwlisuDM0UIL1ruWUBjVR3TBVyuuRWbg7xK3WfnpbQ"
      - "DJANGO_DEBUG=True"
      - "DATABASE_URL=postgres://postgres@db/postgres"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: